# Generated by Django 4.0.5 on 2022-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
