# Generated by Django 4.0.5 on 2022-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
