# Generated by Django 4.0.5 on 2022-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_on_delivery',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
